### ISSUE TITLE
Cool stuff!

### ISSUE THREAD

**Issue by Androxilogin** [victorrjimenezz/4PT-Repository#1] opened 2022-01-29 21:29 UTC
First of all, thanks for this. There seem to be some things that should be mentioned in your tutorial somewhere or from the main page:

1. You cannot use spaces in your .yml. Or even underscores for that matter.

  - pkg/remote_package_installer.pkg in the example repo itself and doesn't show up because of this.

2. Where are downloads stored?

3. When they are removed with the trash can, does that mean they are just deleted from the list or does that remove the pkg file that was transferred?

4. Perhaps add suggestions, like XAMPP as an Apache server, then simply put in your PC address to the main page. 

5. Lighting on the keyboard is hella hard to see. And I had the issue of getting stuck in the address bar after hitting triangle. Muscle memory tells me to hit O once to get back to the list but this is not the case, you'll be transported back to the repo list. It'd be nice to be able to use this. Hitting Triangle then Triangle again crashed the app for me at one point. 

I like how this is shaping up. It will come in really handy for those smaller files.

**Comment by victorrjimenezz** [comment] 2022-01-29 22:02
Hi!! I'm happy you like the project!!
Regarding your concerns:

1. You are completely right, I think the issue is that the path has to be put in side quotation marks "", I'll look further into this, thank you for pointing it out!! :)
2. Currently Downloads are stored in the /user/app directory, as to not need to copy/move the file when installing it
3. When they are removed with the trashcan, they are removed from the list AND from the drive (otherwise there wouldn't be an option to cleanup space and the harddrive would end up filled with garbage 😝)
4. Thank you for this recomendation, I appreciate this feedback and will add it to the tutorial
5. You're right, about both things, regarding lightning on keyboard, I will change it to red color (even though it's "uglier" so as to make it easy to distinguish) in the next version, releasing either today or tomorrow. Regarding controller, will actually add this to the 4PT issues (https://github.com/victorrjimenezz/PS4-4PT/issues/6) , since this seems like a good suggestions and I myself feel like you.

I appreciate your support and love the feedback

**Comment by Androxilogin** [comment] 2022-01-29 23:49
Thank you for considering all of these things!! I'm glad you feel the same way about these things. The quotation marks make sense, like cmd, etc. so it's not an issue, but good to know!

Is there a character limit? And will there be a .yaml creation GUI? I was looking into making one but I really don't know what I'm doing. I haven't messed with that stuff in about 25 years. My idea was to set a location to extract the .yaml so the GUI could remember the location since different users will be using different server programs. Dropdown for GAME, APP, TOOL, MISC, Add or Delete buttons. Maybe run a check on the saved path once it has a destination that checks the folder and Auto-loads whatever is there with the names it finds and gives the ability to change them. Status button showing the current PC IP. Just something simple. 

Oh, and an edit box for changing the repo name/icon whenever.

**Comment by victorrjimenezz** [comment] 2022-01-29 23:57
> Thank you for considering all of these things!! I'm glad you feel the same way about these things. The quotation marks make sense, like cmd, etc. so it's not an issue, but good to know!
> 
> Is there a character limit? And will there be a .yaml creation GUI? I was looking into making one but I really don't know what I'm doing. I haven't messed with that stuff in about 25 years. My idea was to set a location to extract the .yaml so the GUI could remember the location since different users will be using different server programs. Dropdown for GAME, APP, TOOL, MISC, Add or Delete buttons. Maybe run a check on the saved path once it has a destination that checks the folder and Auto-loads whatever is there with the names it finds and gives the ability to change them. Status button showing the current PC IP. Just something simple.

No! There is no character limit!!
Honestly a YAML creator GUI, or maybe even a Repository creator GUI sounds like a GREAT idea, I had not thought of it, I'll get to work on it :). The autoloading feature also seems good! Maybe the repository creator could also be bundled with a simple HTTP server so that you can host the repo from the gui!

EDIT: 
thank you for giving me this feedback, it gives me good ideas that had not even crossed my mind.

**Comment by Androxilogin** [comment] 2022-01-30 00:05
That sounds even more awesome! Thank you for implementing these things. If the HTTP server is added, please add the ability to minimize to the system tray. That is simply a must.

**Comment by Androxilogin** [comment] 2022-01-30 09:40
Two more things I just thought about. 

Once a GUI is implemented, the ability to delete things in the repo from the app perhaps?

Another keyboard request- a 2 second delay movement repeater upon holding the button.

I'm also facing problems with update files not showing up in my list. Stardew Valley specifically at this point. However other games have worked such as Grim Fandango. 

Titles are as: 

Stardew Valley:
  pkgPath: pkg/Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0100-V0100.pkg
  type: GAME
Stardew Valley Update:
  pkgPath: pkg/Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0158-V0100.pkg
  type: MISC
Grim Fandango:
  pkgPath: /pkg/Games/GrimFandango/UP2154-CUSA01319_00-GRIMFANDANGOPS04-A0100-V0101.pkg
  type: GAME
Grim Fandango Update:
  pkgPath: /pkg/Games/GrimFandango/UP2154-CUSA01319_00-GRIMFANDANGOPS04-A0102-V0100.pkg

but I've also tried things as simple as:

Stardew Valley:
  pkgPath: pkg/Games/Stardew1.pkg
  type: GAME
Stardew Valley Update:
  pkgPath: pkg/Games/Stardew2.pkg
  type: MISC
  
So I'm not sure what could be causing it. I checked all sorts of different routes so it must be something internally with the app itself rather than formatting.

**Comment by victorrjimenezz** [comment] 2022-01-30 10:03
> Two more things I just thought about.
> 
> Once a GUI is implemented, the ability to delete things in the repo from the app perhaps?
> 
> Another keyboard request- a 2 second delay movement repeater upon holding the button.
> 
> I'm also facing problems with update files not showing up in my list. Stardew Valley specifically at this point. However other games have worked such as Grim Fandango.
> 
> Titles are as:
> 
> Stardew Valley: pkgPath: pkg/Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0100-V0100.pkg type: GAME Stardew Valley Update: pkgPath: pkg/Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0158-V0100.pkg type: MISC Grim Fandango: pkgPath: /pkg/Games/GrimFandango/UP2154-CUSA01319_00-GRIMFANDANGOPS04-A0100-V0101.pkg type: GAME Grim Fandango Update: pkgPath: /pkg/Games/GrimFandango/UP2154-CUSA01319_00-GRIMFANDANGOPS04-A0102-V0100.pkg
> 
> but I've also tried things as simple as:
> 
> Stardew Valley: pkgPath: pkg/Games/Stardew1.pkg type: GAME Stardew Valley Update: pkgPath: pkg/Games/Stardew2.pkg type: MISC
> 
> So I'm not sure what could be causing it. I checked all sorts of different routes so it must be something internally with the app itself rather than formatting.

I see the ability to delete pkgs from the repo like an interesting feature, maybe, using ftp?
Probably updates are not showing up because of a ""bug"", it should be fixed in the next update, I'm getting it ready and should be available in a few hours tops. (https://github.com/victorrjimenezz/PS4-4PT/issues/3)

EDIT: 
The internal reason that updates are not showing is that the code that reads the PKGs sets it as invalid if some information is missing from the pkg. With themes and updates, since they are not full fledged games, there's information missing, and the app just thinks it's an invalid pkg, but as I said, this should be fixed in the next update. If you check the /user/app/PAPT00200/logs/ folder and check your logfile, it should say something like invalid pkg at: http://..../Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0158-V0100.pkg

**Comment by victorrjimenezz** [comment] 2022-01-30 11:33
> Two more things I just thought about.
> 
> Once a GUI is implemented, the ability to delete things in the repo from the app perhaps?
> 
> Another keyboard request- a 2 second delay movement repeater upon holding the button.
> 
> I'm also facing problems with update files not showing up in my list. Stardew Valley specifically at this point. However other games have worked such as Grim Fandango.
> 
> Titles are as:
> 
> Stardew Valley: pkgPath: pkg/Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0100-V0100.pkg type: GAME Stardew Valley Update: pkgPath: pkg/Games/UP2456-CUSA06840_00-STARDEW00000SIEA-A0158-V0100.pkg type: MISC Grim Fandango: pkgPath: /pkg/Games/GrimFandango/UP2154-CUSA01319_00-GRIMFANDANGOPS04-A0100-V0101.pkg type: GAME Grim Fandango Update: pkgPath: /pkg/Games/GrimFandango/UP2154-CUSA01319_00-GRIMFANDANGOPS04-A0102-V0100.pkg
> 
> but I've also tried things as simple as:
> 
> Stardew Valley: pkgPath: pkg/Games/Stardew1.pkg type: GAME Stardew Valley Update: pkgPath: pkg/Games/Stardew2.pkg type: MISC
> 
> So I'm not sure what could be causing it. I checked all sorts of different routes so it must be something internally with the app itself rather than formatting.
<img width="1392" alt="Bildschirmfoto 2022-01-30 um 12 32 40 PM" src="https://user-images.githubusercontent.com/13591062/151697886-ddde7bb8-8a21-4514-b6ea-371a311bf392.png">
Confirmed! :)

**Comment by victorrjimenezz** [comment] 2022-02-03 23:46
say what? https://github.com/victorrjimenezz/4PT-REPO-GUI 😉

**Comment by Androxilogin** [comment] 2022-02-03 23:54
Ohh maine, you did it! That's awesome! I'm going to check this out right about now.

**Comment by Androxilogin** [comment] 2022-02-04 00:48
Running into some problems at the moment where I'm getting my outside IP address when I start the server. Typing this into the console side fails. I've tried ignoring and going with the local IP which didn't work for me either.

**Comment by victorrjimenezz** [comment] 2022-02-04 01:06
> Running into some problems at the moment where I'm getting my outside IP address when I start the server. Typing this into the console side fails. I've tried ignoring and going with the local IP which didn't work for me either.

darn it, I knew I could not get it first try 😂

Noted, seems like an issue with how the windows version gets the IP Address, I will fix it tomorrow because it‘s 2am here 

ps: basically windows gets the public ip and uses it to host the server, but then the repository will only work if you‘re accessing it from outside the network. It should use the private ip

**Comment by Androxilogin** [comment] 2022-02-04 01:29
I'm about 7 hours behind you here but it's still late for me. I'll keep checking in. Looking pretty promising so far. I figured it was user error so I didn't bother posting it in the issue section.

**Comment by victorrjimenezz** [comment] 2022-02-04 02:24
Fixed it in v1.01 https://github.com/victorrjimenezz/4PT-REPO-GUI/releases/tag/v1.01
it should be working now :)
Now i'm actually going to sleep!

**Closed as completed** 2022-02-09 15:27 UTC
Labels: bug, enhancement
